<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ProductAssociated;

class ProductAssociateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'Epson',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 132,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'Epson',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 150,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ], [
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'Formovie',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 100,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'Formovie',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 120,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'Formovie',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 132,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'Formovie',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 150,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],[
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'Hisense',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 100,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'Hisense',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 120,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'Hisense',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 132,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'Hisense',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 150,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],  [
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'Samsung',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 100,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'Samsung',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 120,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'Samsung',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 132,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'Samsung',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 150,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'BenQ',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 100,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'BenQ',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 120,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'BenQ',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 132,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'BenQ',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 150,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],  [
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'NexiGo',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 100,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'NexiGo',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 120,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'NexiGo',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 132,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08120',
                'parent_product_name' => 'Mayu 120',
                'projector_make' => 'NexiGo',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 150,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],[
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'AWOL',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 100,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'AWOL',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 120,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'AWOL',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 132,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'AWOL',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 150,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],   [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'Epson',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 100,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'Epson',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 120,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'Epson',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 132,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'Epson',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 150,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],  [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'Formovie',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 100,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'Formovie',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 120,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'Formovie',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 132,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'Formovie',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 150,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ], [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'Hisense',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 100,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'Hisense',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 120,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'Hisense',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 132,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'Hisense',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 150,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],  [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'Samsung',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 100,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'Samsung',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 120,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'Samsung',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 132,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'SAMSUNG',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 150,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ], [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'BenQ',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 100,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'BenQ',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 120,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'BenQ',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 132,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'BENQ',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 150,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ], [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'NexiGo',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 100,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'NexiGo',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 120,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'NexiGo',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 132,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
            [
                'parent_product_id' => 'AV08132',
                'parent_product_name' => 'Mishu 132',
                'projector_make' => 'NexiGo',
                'projector_model' => 'All',
                'slot_from_bottom' => null,
                'screensize' => 150,
                'screen_min' => null,
                'screen_max' => null,
                'ceiling_height_min' => null,
                'distance_away_from_screen' => null,
                'distance_of_bottom_section_of_the_screen_from_floor' => null,
                'viewing_angle' => null,
                'hearing_angle' => null,
            ],
        ];

        foreach ($data as $item) {
            ProductAssociated::create($item);
        }
    }
}
