<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProjectorMakeModelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $projectors = [
            ['make' => 'AWOL', 'model' => 'LTV-3500 Pro'],
            ['make' => 'AWOL', 'model' => 'LTV-2500'],
            ['make' => 'AWOL', 'model' => 'LTV-3000 Pro'],
            ['make' => 'AWOL', 'model' => 'LTV-3500'],
            ['make' => 'AWOL', 'model' => 'LTV-2500'],
            ['make' => 'Epson', 'model' => 'EpiqVision Ultra LS800'],
            ['make' => 'Epson', 'model' => 'EpiqVision Ultra LS650'],
            ['make' => 'Epson', 'model' => 'EpiqVision Ultra LS300'],
            ['make' => 'Epson', 'model' => 'BrightLink 760Wi'],
            ['make' => 'Epson', 'model' => 'BrightLink 725Wi'],
            ['make' => 'Epson', 'model' => 'BrightLink 710Ui'],
            ['make' => 'Epson', 'model' => 'BrightLink 695Wi'],
            ['make' => 'Epson', 'model' => 'BrightLink 675Wi'],
            ['make' => 'Epson', 'model' => 'PowerLite 675W'],
            ['make' => 'Epson', 'model' => 'PowerLite 585W'],
            ['make' => 'Formovie', 'model' => 'Formovie Theater'],
            ['make' => 'Formovie', 'model' => 'Formovie Theater Pro'],
            ['make' => 'BenQ', 'model' => 'V7050i'],
            ['make' => 'BenQ', 'model' => 'V5000i'],
            ['make' => 'BenQ', 'model' => 'V6050'],
            ['make' => 'BenQ', 'model' => 'V7000i'],
            ['make' => 'BenQ', 'model' => 'LU960UST'],
            ['make' => 'BenQ', 'model' => 'LU950'],
            ['make' => 'BenQ', 'model' => 'HT3550'],
            ['make' => 'BenQ', 'model' => 'HT2550'],
            ['make' => 'Hisense', 'model' => 'L5G'],
            ['make' => 'Hisense', 'model' => 'L9G'],
            ['make' => 'Hisense', 'model' => 'PX1-PRO'],
            ['make' => 'Hisense', 'model' => 'PX3-Pro'],
            ['make' => 'LG', 'model' => 'HU915QE'],
            ['make' => 'LG', 'model' => 'HU85LA'],
            ['make' => 'LG', 'model' => 'HU70LA'],
            ['make' => 'LG', 'model' => 'HF85JA'],
            ['make' => 'LG', 'model' => 'HF80JA'],
            ['make' => 'LG', 'model' => 'PF1000U'],
            ['make' => 'LG', 'model' => 'PH450UG'],
            ['make' => 'LG', 'model' => 'HF65LS'],
            ['make' => 'LG', 'model' => 'HF80LSR'],
            ['make' => 'LG', 'model' => 'HF85LSR'],
            ['make' => 'LG', 'model' => 'PW800'],
            ['make' => 'LG', 'model' => 'PB63U'],
            ['make' => 'LG', 'model' => 'HF65LS'],
            ['make' => 'LG', 'model' => 'HF85LS'],
            ['make' => 'LG', 'model' => 'HF80LS'],
            ['make' => 'Optoma', 'model' => 'GT3500HDR'],
            ['make' => 'Optoma', 'model' => 'UHZ65UST'],
            ['make' => 'Optoma', 'model' => 'CinemaX P2'],
            ['make' => 'Optoma', 'model' => 'CinemaX P1'],
            ['make' => 'Optoma', 'model' => 'HZ39HDR'],
            ['make' => 'Optoma', 'model' => 'GT1090HDR'],
            ['make' => 'Optoma', 'model' => 'GT1080HDR'],
            ['make' => 'Optoma', 'model' => 'GT1080HDR+'],
            ['make' => 'Optoma', 'model' => 'GT760'],
            ['make' => 'Optoma', 'model' => 'EH320UST'],
            ['make' => 'Optoma', 'model' => 'EH330UST'],
            ['make' => 'Optoma', 'model' => 'EH335'],
            ['make' => 'Optoma', 'model' => 'EH345'],
            ['make' => 'Optoma', 'model' => 'EH415ST'],
            ['make' => 'Optoma', 'model' => 'EH460ST'],
            ['make' => 'Optoma', 'model' => 'EH461'],
            ['make' => 'Optoma', 'model' => 'EH500'],
            ['make' => 'Optoma', 'model' => 'EH505'],
            ['make' => 'Optoma', 'model' => 'EH505e'],
            ['make' => 'Optoma', 'model' => 'W340UST'],
            ['make' => 'Optoma', 'model' => 'W345'],
            ['make' => 'Optoma', 'model' => 'W355'],
            ['make' => 'Optoma', 'model' => 'X340UST'],
            ['make' => 'Optoma', 'model' => 'X345'],
            ['make' => 'Optoma', 'model' => 'X355'],
            ['make' => 'Optoma', 'model' => 'ZH406ST'],
            ['make' => 'Optoma', 'model' => 'ZH420UST'],
            ['make' => 'Optoma', 'model' => 'ZH420USTi'],
            ['make' => 'Optoma', 'model' => 'ZW300UST'],
            ['make' => 'Samsung', 'model' => 'The Premiere 8K'],
            ['make' => 'Samsung', 'model' => 'The Premiere 9'],
            ['make' => 'Samsung', 'model' => 'The Premiere 7'],
            ['make' => 'Samsung', 'model' => 'The Premiere 5'],
            ['make' => 'Samsung', 'model' => 'The Premiere LSP9T'],
            ['make' => 'Samsung', 'model' => 'The Premiere LSP7T'],
            ['make' => 'Vava', 'model' => 'VAVA 4K Ultra Short Throw Laser TV'],
            ['make' => 'Vava', 'model' => 'VAVA Chroma'],
            ['make' => 'Vava', 'model' => 'VAVA LT002-W'],
            ['make' => 'ViewSonic', 'model' => 'X2000B-4K'],
            ['make' => 'ViewSonic', 'model' => 'LS831WU'],
            ['make' => 'ViewSonic', 'model' => 'LS800HD'],
            ['make' => 'ViewSonic', 'model' => 'LS700HD'],
            ['make' => 'ViewSonic', 'model' => 'LS600W'],
            ['make' => 'ViewSonic', 'model' => 'LS500W'],
            ['make' => 'ViewSonic', 'model' => 'LS500WP'],
            ['make' => 'ViewSonic', 'model' => 'LS500Z'],
            ['make' => 'ViewSonic', 'model' => 'LS500ZP'],
            ['make' => 'XGIMI', 'model' => 'XGIMI Aura'],
            ['make' => 'XGIMI', 'model' => 'XGIMI Horizon Ultra'],
            ['make' => 'XGIMI', 'model' => 'XGIMI Horizon Pro'],
            ['make' => 'XGIMI', 'model' => 'XGIMI Horizon'],
            ['make' => 'XGIMI', 'model' => 'XGIMI MoGo Pro'],
            ['make' => 'XGIMI', 'model' => 'XGIMI MoGo Pro+'],
            ['make' => 'XGIMI', 'model' => 'XGIMI Elfin'],
            ['make' => 'Sony', 'model' => 'VPL-SW535'],
            ['make' => 'Sony', 'model' => 'VPL-FHZ55'],
            ['make' => 'Sony', 'model' => 'LSPX-W1S'],
            ['make' => 'Sony', 'model' => 'LSPX-P1'],
            ['make' => 'Wemax', 'model' => 'Nova'],
            ['make' => 'Wemax', 'model' => 'Nova SE'],
            ['make' => 'Wemax', 'model' => 'Dice'],
            ['make' => 'Wemax', 'model' => 'Prime'],
            ['make' => 'Wemax', 'model' => 'Cine'],
            ['make' => 'Vankyo', 'model' => 'Leisure 510 Pro'],
            ['make' => 'Vankyo', 'model' => 'Leisure 510'],
            ['make' => 'Vankyo', 'model' => 'Vista T4'],
            ['make' => 'Yaber', 'model' => 'Y31'],
            ['make' => 'Dangbei', 'model' => 'Mars Pro'],
            ['make' => 'Dangbei', 'model' => 'Mars II Pro'],
            ['make' => 'Dangbei', 'model' => 'Atom'],
            ['make' => 'Kodak', 'model' => 'Freeview P20'],
            ['make' => 'Bomaker', 'model' => 'Polaris 4K'],
            ['make' => 'Bomaker', 'model' => 'Polaris'],
            ['make' => 'Xiaomi', 'model' => 'Mi 4K 150"'],
            ['make' => 'Xiaomi', 'model' => 'Fengmi C2 / Formovie 4K'],
            ['make' => 'Dell', 'model' => 'S718QL']
        ];

        DB::table('projector_make_models')->insert($projectors);
    }
}
